# Generated by Django 3.0.6 on 2020-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
